// data.js - Student data for Elite Hostel

const studentData = [
    // Floor 1 Students
    {
        id: 1,
        name: "Sonam Dorji",
        indexNumber: "07230043",
        phone: "07230043",
        parentPhone: "17507421",
        floor: 2,
        image: "sonam dorji.jpg",
        roomNumber: "213",
        year: 3,
        semester: "3rd",
        course: "BSc DSDA",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "AB+"
    },
    {
        id: 2,
        name: "Gyembo Wangchuk",
        indexNumber: "07230028",
        phone: "+975 17897749",
        parentPhone: "+975 17712893",
        floor: 2,
        image: "gyembo.jpg",
        roomNumber: "211",
        year: 3,
        semester: "1st semester",
        course: "BSc DSDA",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "A+"
    },
    {
        id: 3,
        name: "Cheki Dorji",
        indexNumber: "07230004",
        phone: "+975 17977533",
        parentPhone: "+975 77675665",
        floor: 2,
        image: "cheki dorji.jpg",
        roomNumber: "212",
        year: 3,
        semester: "1st Semester",
        course: "BSc DSDA",
        Government_type: "Government",
        Health_issue: "Nothing",
        bloodType: "O+"
    },
    {
        id: 4,
        name: "Sherub loday",
        indexNumber: "07230164",
        phone: "+975 17955394",
        parentPhone: "+975 17631996",
        floor: 2,
        image: "Sherub.jpg",
        roomNumber: "213",
        year: 3,
        semester: "1st Semester",
        course: "BSc Physic",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "B+"
    },
    {
        id: 5,
        name: "Tshering Nidup",
        indexNumber: "07220027",
        phone: "+975 17691256",
        parentPhone: "+975 17875472",
        floor: 2,
        image: "tshering nidup.jpg",
        roomNumber: "214",
        year: 4,
        semester: "1st Semester",
        course: "BSc Data science",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "A+"
    },
    {
        id: 6,
        name: "Tula Ram Gurung",
        indexNumber: "07230118",
        phone: "+975 17778502",
        parentPhone: "+975 77684588",
        floor: 2,
        image: "tula.jpg",
        roomNumber: "210",
        year: 3,
        semester: "1st Semester",
        course: "BSc Math",
        Government_type: "Government scholarship",
        Health_issue: "None",
        bloodType: "A+"
    },
    {
        id: 7,
        name: "Ati Raj Dhakal",
        indexNumber: "07230093",
        phone: "+975 17857338",
        parentPhone: "+975 77785575",
        floor: 2,
        image: "ati.jpg",
        roomNumber: "208",
        year: 3,
        semester: "1st Semester",
        course: "BSc Math",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "o+"
    },
    {
        id: 8,
        name: "Ranjit Rai",
        indexNumber: "07230107",
        phone: "+975 77313141",
        parentPhone: "+975 77375087",
        floor: 2,
        image: "ranjit.jpg",
        roomNumber: "207",
        year: 3,
        semester: "1st Semester",
        course: "BSc Math",
        Government_type: "Governemnt",
        Health_issue: "None",
        bloodType: "O+"
    },
    {
        id: 9,
        name: "Dorji Tenzin",
        indexNumber: "07230124",
        phone: "+975 17542743",
        parentPhone: "+975 17445827",
        floor: 2,
        image: "dorji tenzin.jpg",
        roomNumber: "",
        year: 3,
        semester: "1st Semester",
        course: "BSc life science",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "B+"
    },
    {
        id: 10,
        name: "Anup Gurung",
        indexNumber: "07230210",
        phone: "+975 1780524",
        parentPhone: "+975 77730401",
        floor: 2,
        image: "anup.jpg",
        roomNumber: "205",
        year: 3,
        semester: "1st Semester",
        course: "BSc DSDA",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "AB+"
    },
    {
        id: 11,
        name: "Pema Namgay",
        indexNumber: "07230019",
        phone: "+975 17499519",
        parentPhone: "+975 17770964",
        floor: 2,
        image: "pema namgay.jpg",
        roomNumber: "205",
        year: 3,
        semester: "1st Semester",
        course: "BSc DSDA",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: ""
    },
    {
        id: 12,
        name: "Lilla Dhar Dungana",
        indexNumber: "07230131",
        phone: "+975 77407228",
        parentPhone: "+975 77222771",
        floor: 2,
        image: "lila.jpg",
        roomNumber: "204",
        year: 3,
        semester: "1st Semester",
        course: "BSc Life science",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: ""
    },
    {
        id: 13,
        name: "Ram Kumar Rai",
        indexNumber: "07220042",
        phone: "+975 77255059",
        parentPhone: "+975 17505384",
        floor: 2,
        image: "ram.jpg",
        roomNumber: "203",
        year: 4,
        semester: "1st Semester",
        course: "BSc Data science",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "O+"
    },
    {
        id: 14,
        name: "Sonam Chophel",
        indexNumber: "07230061",
        phone: "+975 17722386",
        parentPhone: "+975 17976492",
        floor: 3,
        image: "sonam chophel.jpg",
        roomNumber: "114",
        year: 3,
        semester: "1st Semester",
        course: "BSc DSDA",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "A+"
    },
    {
        id: 15,
        name: "Kinzang Norbu",
        indexNumber: "07230208",
        phone: "+975 17646725",
        parentPhone: "+975 17954399",
        floor: 1,
        image: "kinzang norbu.jpg",
        roomNumber: "110",
        year: 3,
        semester: "1st Semester",
        course: "BA Economic and political science",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "B+"
    },
    {
        id: 16,
        name: "Tenzin kelzang Dorji",
        indexNumber: "07230170",
        phone: "+975 17990964",
        parentPhone: "+975 17536700",
        floor: 1,
        image: "TKD.jpg",
        roomNumber: "104",
        year: 2,
        semester: "1st Semester",
        course: "BSc Physic",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "o+"
    },
    {
        id: 17,
        name: "Dorji Tshering",
        indexNumber: "07210381",
        phone: "+975 17622329",
        parentPhone: "+975 17821435",
        floor: 1,
        image: "dorji tshering.jpg",
        roomNumber: "111",
        year: 4,
        semester: "1st Semester",
        course: "BSc Data Science",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "AB+"
    },
    {
        id: 18,
        name: "Sangay Rinchen",
        indexNumber: "07210136",
        phone: "+975 77217491",
        parentPhone: "+975 17694094",
        floor: 1,
        image: "sangay rinchen.jpg",
        roomNumber: "108",
        year: 3,
        semester: "1st Semester",
        course: "BSc Math",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "B+"
    },
    
    // Floor 2 Students
    {
        id: 19,
        name: "Deepak Gurung",
        indexNumber: "07240157",
        phone: "+975 17795275",
        parentPhone: "+975 77283717",
        floor: 1,
        image: "deepak.jpg",
        roomNumber: "106",
        year: 2,
        semester: "1st Semester",
        course: "BSc Physic",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "O+"
    },
    {
        id: 20,
        name: "Passang Dorji",
        indexNumber: "07220014",
        phone: "+975 77735279",
        parentPhone: "+975 17818140",
        floor: 1,
        image: "passang.jpg",
        roomNumber: "107",
        year: 4,
        semester: "1st Semester",
        course: "BSc Data science",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "o+"
    },
    {
        id: 21,
        name: "Asbeeni Kumar Kafley",
        indexNumber: "07220287",
        phone: "+975 17817092",
        parentPhone: "+975 17416652",
        floor: 1,
        image: "asbeen.jpg",
        roomNumber: "102",
        year: 3,
        semester: "1st Semester",
        course: "BSc Math",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "o+"
    },
    {
        id: 22,
        name: "Thinley Norbu",
        indexNumber: "07230115",
        phone: "+975 17700952",
        parentPhone: "+975 77852758",
        floor: 1,
        image: "thinley norbu.jpg",
        roomNumber: "105",
        year: 3,
        semester: "1st Semester",
        course: "BSc Math",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "AB+"
    },
    {
        id: 23,
        name: "Cheki Leythro",
        indexNumber: "07240155",
        phone: "+975 77492372",
        parentPhone: "+975 17243047",
        floor: 1,
        image: "cheki leythro.jpg",
        roomNumber: "113",
        year: 2,
        semester: "1st Semester",
        course: "BSc Physic",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "AB+"
    },
    {
        id: 24,
        name: "Pema Lethro Dorji",
        indexNumber: "07240170",
        phone: "+975 17454323",
        parentPhone: "+975 17497176",
        floor: 1,
        image: "pema leythro.jpg",
        roomNumber: "113",
        year: 2,
        semester: "1st Semester",
        course: "BSc Physic",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "O+"
    },
    {
        id: 25,
        name: "Jigme Peljor",
        indexNumber: "07240217",
        phone: "+975 17348005",
        parentPhone: "+975 17483924",
        floor: 3,
        image: "jigme peljor.jpg",
        roomNumber: "304",
        year: 2,
        semester: "1st Semester",
        course: "BSc Math",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "B+"
    },
    {
        id: 26,
        name: "Sonam Singye",
        indexNumber: "07240235",
        phone: "+975 17329152",
        parentPhone: "+975 17509127",
        floor: 1,
        image: "sonam singye.jpg",
        roomNumber: "103",
        year: 2,
        semester: "1st Semester",
        course: "BSc Math",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: ""
    },
    {
        id: 27,
        name: "Jigme Yoezer Thinley",
        indexNumber: "07240219",
        phone: "+975 17527803",
        parentPhone: "+975 17958137",
        floor: 1,
        image: "jigme yoezer thinley.jpg",
        roomNumber: "103",
        year: 2,
        semester: "1st Semester",
        course: "BSc Math",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "AB+"
    },
    {
        id: 28,
        name: "Tshering Dorji",
        indexNumber: "07240243",
        phone: "+975 17802123",
        parentPhone: "+975 17695660",
        floor: 1,
        image: "tshering dorji.jpg",
        roomNumber: "104",
        year: 2,
        semester: "1st Semester",
        course: "BSc Math",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "A+"
    },
    {
        id: 29,
        name: "Sonam Tobgay",
        indexNumber: "07240146",
        phone: "+975 77425837",
        parentPhone: "+975 17415311",
        floor: 1,
        image: "sonam tobgay.jpg",
        roomNumber: "106",
        year: 2,
        semester: "1st Semester",
        course: "BSc Life Science",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "A+"
    },
    {
        id: 30,
        name: "Karma Wangda",
        indexNumber: "07230209",
        phone: "+975 17276463",
        parentPhone: "+975 17741088",
        floor: 3,
        image: "karma wangda.jpg",
        roomNumber: "316",
        year: 2,
        semester: "1st Semester",
        course: "BSc Math",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "O+"
    },
    {
        id: 31,
        name: "Ngawang Jigme",
        indexNumber: "07240046",
        phone: "+975 77655701",
        parentPhone: "+975 17638572",
        floor: 3,
        image: "ngawang jigme.jpg",
        roomNumber: "313",
        year: 2,
        semester: "1st Semester",
        course: "BSc DSDA",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: ""
    },
    {
        id: 32,
        name: "Tandin Tshewang",
        indexNumber: "07240055",
        phone: "+975 17970981",
        parentPhone: "+975 17610626",
        floor: 3,
        image: "tandin tshewang.jpg",
        roomNumber: "313",
        year: 2,
        semester: "1st Semester",
        course: "BSc DSDA",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "O+"
    },
    {
        id: 33,
        name: "Yeshi Rabgay",
        indexNumber: "07230092",
        phone: "+975 17858493",
        parentPhone: "+975 17772078",
        floor: 3,
        image: "yeshi rabs.jpg",
        roomNumber: "312",
        year: 3,
        semester: "1st Semester",
        course: "B DCPM",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "A+"
    },
    {
        id: 34,
        name: "Karma Pema Keltshel",
        indexNumber: "07230099",
        phone: "+975 17734151",
        parentPhone: "+975 17766779",
        floor: 3,
        image: "KPK.jpg",
        roomNumber: "311",
        year: 3,
        semester: "1st Semester",
        course: "BSc Math",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "O+"
    },
    {
        id: 35,
        name: "Kuenga Yoezer",
        indexNumber: "07240165",
        phone: "+975 77744773",
        parentPhone: "+975 17609060",
        floor: 3,
        image: "kunga yoezer.jpg",
        roomNumber: "310",
        year: 2,
        semester: "1st Semester",
        course: "BSc Physic",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "B+"
    },
    {
        id: 36,
        name: "Sanjit Rai",
        indexNumber: "07240204",
        phone: "+975 77472313",
        parentPhone: "+975 77375087",
        floor: 3,
        image: "Sanjit Rai.jpg",
        roomNumber: "306",
        year: 2,
        semester: "1st Semester",
        course: "BSc Chemistry",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: ""
    },
    
    // Floor 3 Students
    {
        id: 37,
        name: "Sanjay Rai",
        indexNumber: "07240203",
        phone: "+975 77204516",
        parentPhone: "+975 17764379",
        floor: 3,
        image: "sanjay.jpg",
        roomNumber: "306",
        year: 2,
        semester: "1st Semester",
        course: "BSc Chemistry",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: ""
    },
    {
        id: 38,
        name: "Ashik Rai",
        indexNumber: "07230177",
        phone: "+975 17626063",
        parentPhone: "+975 77886949",
        floor: 3,
        image: "Ashik Rai.jpg",
        roomNumber: "305",
        year: 3,
        semester: "1st Semester",
        course: "BSc Math",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "O+"
    },
    {
        id: 39,
        name: "Madav Dulal",
        indexNumber: "07230132",
        phone: "+975 17350404",
        parentPhone: "+975 77384450",
        floor: 3,
        image: "madav.jpg",
        roomNumber: "314",
        year: 3,
        semester: "1st Semester",
        course: "BSc Life Science",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "A+"
    },
    {
        id: 40,
        name: "Ugyen jigme Lhendup",
        indexNumber: "07230086",
        phone: "+975 17705629",
        parentPhone: "+975 17677946",
        floor: 3,
        image: "Sonam Tenzin.jpg",
        roomNumber: "308",
        year: 3,
        semester: "1st Semester",
        course: "B DCPM",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "B+"
    },
    {
        id: 41,
        name: "Ugyen ChopHel",
        indexNumber: "07230201",
        phone: "+975 77292279",
        parentPhone: "+975 77283798",
        floor: 1,
        image: "ugyen c.jpg",
        roomNumber: "100",
        year: 3,
        semester: "1st Semester",
        course: "BSc Chemistry",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "A+"
    },
    {
        id: 42,
        name: "Sonam Yeshi",
        indexNumber: "07230114",
        phone: "+975 77810425",
        parentPhone: "+975 17678990",
        floor: 1,
        image: "sonam yeshi.jpg",
        roomNumber: "306",
        year: 3,
        semester: "1st Semester",
        course: "BSc Math",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "O+"
    },
    {
        id: 43,
        name: "Pema wangdi",
        indexNumber: "07230074",
        phone: "+975 77623813",
        parentPhone: "+975 77765619",
        floor: 1,
        image: "pema wangdi.jpg",
        roomNumber: "112",
        year: 3,
        semester: "1st Semester",
        course: "BSc DSDA",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "B+"
    },
    {
        id: 44,
        name: "Ngawang Gyeltshen",
        indexNumber: "07230189",
        phone: "+975 17990886",
        parentPhone: "+975 17480308",
        floor: 1,
        image: "ngawang gyeltshen.jpg",
        roomNumber: "114",
        year: 3,
        semester: "1st Semester",
        course: "BSc Chemistry",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "B+"
    },
    {
        id: 45,
        name: "Tashi Wangdi",
        indexNumber: "07230067",
        phone: "+975 17918117",
        parentPhone: "+975 17484545",
        floor: 1,
        image: "tashi wangdi.jpg",
        roomNumber: "114",
        year: 3,
        semester: "1st Semester",
        course: "BA Economic and political science",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "A+"
    },
    {
        id: 46,
        name: "Kezang Dorji",
        indexNumber: "07230032",
        phone: "+975 17300882",
        parentPhone: "+975 77420123",
        floor: 2,
        image: "kezang dorji.jpg",
        roomNumber: "216",
        year: 3,
        semester: "1st Semester",
        course: "B DCPM",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "B+"
    },
    {
        id: 47,
        name: "Kuenga Lhendup lhagey",
        indexNumber: "07240227",
        phone: "+975 17517655",
        parentPhone: "+975 17660992",
        floor: 3,
        image: "lhagey.jpg",
        roomNumber: "310",
        year: 3,
        semester: "1st Semester",
        course: "BSc MAth",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "B+"
    },
    {
        id: 48,
        name: "Leki Khandu",
        indexNumber: "07240199",
        phone: "+975 77391645",
        parentPhone: "+975 77658546",
        floor: 3,
        image: "leki khandu.jpg",
        roomNumber: "304",
        year: 2,
        semester: "1st Semester",
        course: "BSc Chemistry",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "o+"
    },
    {
        id: 49,
        name: "Ugyen Thinley",
        indexNumber: "07230204",
        phone: "+975 77848105",
        parentPhone: "+975 17404374",
        floor: 3,
        image: "ut.jpg",
        roomNumber: "301",
        year: 3,
        semester: "1st Semester",
        course: "BSc Chemistry",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "AB+"
    },
    {
        id: 50,
        name: "Tandin Ghalley",
        indexNumber: "07230169",
        phone: "+975 17960889",
        parentPhone: "+975 17675013",
        floor: 3,
        image: "tandin ghalley.jpg",
        roomNumber: "302",
        year: 3,
        semester: "1st Semester",
        course: "BSc Physic",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "O+"
    },
    {
        id: 51,
        name: "Jampel Dorji",
        indexNumber: "07240068",
        phone: "+975 77445409",
        parentPhone: "+975 17929082",
        floor: 3,
        image: "jample dorji.jpg",
        roomNumber: "301",
        year: 2,
        semester: "1st Semester",
        course: "BSc DSDA",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "o+"
    },
    {
        id: 52,
        name: "Thinely Dorji",
        indexNumber: "07240116",
        phone: "+975 77603757",
        parentPhone: "+975 17780811",
        floor: 3,
        image: "thinley dorji.jpg",
        roomNumber: "316",
        year: 2,
        semester: "Fall Semester",
        course: "BSc DSDA",
        Government_type: "Private",
        Health_issue: "None",
        bloodType: "B+"
    },
    {
        id: 53,
        name: "Ugyen Peljor",
        indexNumber: "07230068",
        phone: "+975 17807094",
        parentPhone: "+975 17710987",
        floor: 3,
        image: "ugyen peljor.jpg",
        roomNumber: "309",
        year: 3,
        semester: "1st Semester",
        course: "B DCPM",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "o+"
    },
    {
        id: 54,
        name: "Lham Tshering ",
        indexNumber: "07240016",
        phone: "17303488",
        parentPhone: "17849422",
        floor: 2,
        image: "lham.jpg",
        roomNumber: "216",
        year: 2,
        semester: "1st semester",
        course: "BSc EPS",
        Government_type: "Government",
        Health_issue: "None",
        bloodType: "AB+"
    },
];

// Export the data for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { studentData };
} else {
    // For browser environments
    window.studentData = studentData;

}
